platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/compute-image-tools-test/((image-name))
    tag: latest
    username: _json_key
    password: ((concourse-sa.credential))

inputs:
- name: credentials
- name: guest-test-infra

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: ./main
  args:
