platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/compute-image-tools-test/((repo-name))-tests
    tag: latest

inputs:
- name: credentials
- name: guest-test-infra

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: sh
  args:
  - -exc
  - |
    ./wrapper ./e2e_tests
